# Generated by Django 3.2 on 2023-04-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0003_tasks_geeks_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='geeks_field',
        ),
        migrations.AddField(
            model_name='tasks',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
