# Generated by Django 3.2 on 2023-04-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0004_auto_20230402_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tasks',
            name='end_time_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_time_date',
            field=models.DateTimeField(null=True),
        ),
    ]
